### ISSUE TITLE
大佬有bug

### ISSUE THREAD

**Issue by jiuchu** [kuku3863/sign_weibo_chaohua#2]
只能签到第一页 后面的不签到

**Comment by kuku3863** [comment]
好的，我试试哈，因为是最近才接触，关注的有点少。

**Comment by jiuchu** [comment]
> 好的，我试试哈，因为是最近才接触，关注的有点少。

大佬修复了吗 好像只能签到15还是20个

**Comment by kuku3863** [comment]
> > 好的，我试试哈，因为是最近才接触，关注的有点少。
> 
> 大佬修复了吗 好像只能签到15还是20个

可以了，新版本添加了一个count参数，可能不够严谨，我发现了since_id={"manage":"","follow":"xxxxxx","page":2} 里面是有page的，但是第一页这个值是没有到，并且，如果只有2页，page给3还是在第二页，目前count调大，能满足基本需求了，后续我 在看看有什么好的解决办法。

**Comment by kuku3863** [comment]
> > > 好的，我试试哈，因为是最近才接触，关注的有点少。
> > 
> > 
> > 大佬修复了吗 好像只能签到15还是20个
> 
> 可以了，新版本添加了一个count参数，可能不够严谨，我发现了since_id={"manage":"","follow":"xxxxxx","page":2} 里面是有page的，但是第一页这个值是没有的，并且，如果只有2页，page给3还是在第二页，目前count调大，能满足基本需求了，后续我 在看看有什么好的解决办法。

![image](https://github.com/kuku3863/sign_weibo_chaohua/assets/82189649/1fb7b6c9-dd12-4e9b-b005-c64d7045e9a8)
我测试的，我26个关注全部成功。后续还有什么问题，可以继续提出来哈

**Comment by jiuchu** [comment]
> > > > 好的，我试试哈，因为是最近才接触，关注的有点少。
> > > 
> > > 
> > > 大佬修复了吗 好像只能签到15还是20个
> > 
> > 
> > 可以了，新版本添加了一个count参数，可能不够严谨，我发现了since_id={"manage":"","follow":"xxxxxx","page":2} 里面是有page的，但是第一页这个值是没有的，并且，如果只有2页，page给3还是在第二页，目前count调大，能满足基本需求了，后续我 在看看有什么好的解决办法。
> 
> ![image](https://user-images.githubusercontent.com/82189649/258708913-1fb7b6c9-dd12-4e9b-b005-c64d7045e9a8.png) 我测试的，我26个关注全部成功。后续还有什么问题，可以继续提出来哈

   for i 在 range(max_retries):  20行怎么有中文

**Comment by jiuchu** [comment]
救命........这代码好多都是中文符号阿 ,和。

**Comment by kuku3863** [comment]
> 救命........这代码好多都是中文符号阿 ,和。

可以了，再试试

**Comment by jiuchu** [comment]
> > 救命........这代码好多都是中文符号阿 ,和。
> 
> 可以了，再试试

可以了感谢
