### ISSUE TITLE
还有点问题

### ISSUE THREAD

**Issue by jiuchu** [kuku3863/sign_weibo_chaohua#3]
145个超话 有7个没有签到

**Comment by kuku3863** [comment]
好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看

**Comment by jiuchu** [comment]
> 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)

第一次运行 请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
请求失败，原因: HTTP Error: 427。5秒后重试...
HTTP Error: 427
第二次没有报错 但是也没签到剩下的 明天看看吧

**Comment by jiuchu** [comment]
> 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)

今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试

**Comment by kuku3863** [comment]
> > 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)
> 
> 今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试

我关注了181个，昨晚运行了，没出现问题，你吧出现问题的几个超话截图给我看看吧，我分析下

**Comment by kuku3863** [comment]
> 
查了相关文档，应该是请求量过多了，被拒绝了

**Comment by kuku3863** [comment]
> > > 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)
> > 
> > 
> > 今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试
> 
> 我关注了181个，昨晚运行了，没出现问题，你吧出现问题的几个超话截图给我看看吧，我分析下

我看了下，是请求量过多了被拒绝了，所以出现427，不过没关系，代码做的是重新尝试，过会就好了， 我的200个关注，全部签到成功了

**Comment by kuku3863** [comment]
> > > > 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)
> > > 
> > > 
> > > 今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试
> > 
> > 
> > 我关注了181个，昨晚运行了，没出现问题，你吧出现问题的几个超话截图给我看看吧，我分析下
> 
> 我看了下，是请求量过多了被拒绝了，所以出现427，不过没关系，代码做的是重新尝试，过会就好了， 我的200个关注，全部签到成功了

![image](https://github.com/kuku3863/sign_weibo_chaohua/assets/82189649/57e7844c-9a0f-4e3b-85ee-2b6f5a6f2279)

**Comment by jiuchu** [comment]
> > > > > 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)
> > > > 
> > > > 
> > > > 今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试
> > > 
> > > 
> > > 我关注了181个，昨晚运行了，没出现问题，你吧出现问题的几个超话截图给我看看吧，我分析下
> > 
> > 
> > 我看了下，是请求量过多了被拒绝了，所以出现427，不过没关系，代码做的是重新尝试，过会就好了， 我的200个关注，全部签到成功了
> 
> ![image](https://user-images.githubusercontent.com/82189649/258960176-57e7844c-9a0f-4e3b-85ee-2b6f5a6f2279.png)

难道我抓包有问题？试试梦幻西游网页版

**Comment by kuku3863** [comment]
> > > > > > 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)
> > > > > 
> > > > > 
> > > > > 今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试
> > > > 
> > > > 
> > > > 我关注了181个，昨晚运行了，没出现问题，你吧出现问题的几个超话截图给我看看吧，我分析下
> > > 
> > > 
> > > 我看了下，是请求量过多了被拒绝了，所以出现427，不过没关系，代码做的是重新尝试，过会就好了， 我的200个关注，全部签到成功了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/82189649/258960176-57e7844c-9a0f-4e3b-85ee-2b6f5a6f2279.png)
> 
> 难道我抓包有问题？试试梦幻西游网页版

我看了下，跟什么超话是没关系的，只要是超话，都有一个链接，是微博那边做了处理，出现427不用管，代码会继续请求，看我上面的截图，后续他会成功了，微博那边应该是一定时间签到了多少个会触发保护机制。

**Comment by jiuchu** [comment]
> > > > > > > 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)
> > > > > > 
> > > > > > 
> > > > > > 今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试
> > > > > 
> > > > > 
> > > > > 我关注了181个，昨晚运行了，没出现问题，你吧出现问题的几个超话截图给我看看吧，我分析下
> > > > 
> > > > 
> > > > 我看了下，是请求量过多了被拒绝了，所以出现427，不过没关系，代码做的是重新尝试，过会就好了， 我的200个关注，全部签到成功了
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/82189649/258960176-57e7844c-9a0f-4e3b-85ee-2b6f5a6f2279.png)
> > 
> > 
> > 难道我抓包有问题？试试梦幻西游网页版
> 
> 我看了下，跟什么超话是没关系的，只要是超话，都有一个链接，是微博那边做了处理，出现427不用管，代码会继续请求，看我上面的截图，后续他会成功了，微博那边应该是一定时间签到了多少个会触发保护机制。

今天没427了........但是就是有几个没签到成功

**Comment by kuku3863** [comment]
> > > > > > > > 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试
> > > > > > 
> > > > > > 
> > > > > > 我关注了181个，昨晚运行了，没出现问题，你吧出现问题的几个超话截图给我看看吧，我分析下
> > > > > 
> > > > > 
> > > > > 我看了下，是请求量过多了被拒绝了，所以出现427，不过没关系，代码做的是重新尝试，过会就好了， 我的200个关注，全部签到成功了
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/82189649/258960176-57e7844c-9a0f-4e3b-85ee-2b6f5a6f2279.png)
> > > 
> > > 
> > > 难道我抓包有问题？试试梦幻西游网页版
> > 
> > 
> > 我看了下，跟什么超话是没关系的，只要是超话，都有一个链接，是微博那边做了处理，出现427不用管，代码会继续请求，看我上面的截图，后续他会成功了，微博那边应该是一定时间签到了多少个会触发保护机制。
> 
> 今天没427了........但是就是有几个没签到成功

那你吧那些没签到的超话名称给我，我分析下他们的元素

**Comment by jiuchu** [comment]
> > > > > > > > > 好的，我修改了逻辑，添加了一些容错，你再测测，或者明天签到的时候再看看。 ![image](https://user-images.githubusercontent.com/82189649/258794286-401be98b-a60b-4992-853b-459c84ab9475.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 今天又试了 没报错 但是那几个还是没签到成功 要不你也关注145个试试
> > > > > > > 
> > > > > > > 
> > > > > > > 我关注了181个，昨晚运行了，没出现问题，你吧出现问题的几个超话截图给我看看吧，我分析下
> > > > > > 
> > > > > > 
> > > > > > 我看了下，是请求量过多了被拒绝了，所以出现427，不过没关系，代码做的是重新尝试，过会就好了， 我的200个关注，全部签到成功了
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/82189649/258960176-57e7844c-9a0f-4e3b-85ee-2b6f5a6f2279.png)
> > > > 
> > > > 
> > > > 难道我抓包有问题？试试梦幻西游网页版
> > > 
> > > 
> > > 我看了下，跟什么超话是没关系的，只要是超话，都有一个链接，是微博那边做了处理，出现427不用管，代码会继续请求，看我上面的截图，后续他会成功了，微博那边应该是一定时间签到了多少个会触发保护机制。
> > 
> > 
> > 今天没427了........但是就是有几个没签到成功
> 
> 那你吧那些没签到的超话名称给我，我分析下他们的元素

梦幻西游网页版 最强蜗牛 阴阳师手游 战争怒吼 我的世界中国版 rita小雨桑

**Comment by kuku3863** [comment]
> 最强蜗牛

![1691462967768](https://github.com/kuku3863/sign_weibo_chaohua/assets/82189649/390e756e-bddd-4fee-94ee-b57bcf22f8f0)
![1691462965862](https://github.com/kuku3863/sign_weibo_chaohua/assets/82189649/93cf965c-df7d-461b-830f-946e073e9be6)
看他参数也没问题，我执行这几个也没问题，现在没办法复现你的情况，暂时不知道哪里导致的

**Comment by kuku3863** [comment]
> 最强蜗牛

看看代码是不是最新的，因为我最后改的逻辑，他会判断是否还有未签到的，如果没有报错的情况下，应该是不会存在漏签的

**Comment by jiuchu** [comment]
> > 最强蜗牛
> 
> 看看代码是不是最新的，因为我最后改的逻辑，他会判断是否还有未签到的，如果没有报错的情况下，应该是不会存在漏签的

是最新的 我还重新抓包吧 要不你留个邮箱 我把ck发你

**Comment by kuku3863** [comment]
> > > 最强蜗牛
> > 
> > 
> > 看看代码是不是最新的，因为我最后改的逻辑，他会判断是否还有未签到的，如果没有报错的情况下，应该是不会存在漏签的
> 
> 是最新的 我还重新抓包了 要不你留个邮箱 我把ck发你
386392685@qq.com
