### ISSUE TITLE
在pc里运行如何修改呢？

### ISSUE THREAD

**Issue by jiuchu** [kuku3863/sign_weibo_chaohua#4]
params =“环境变量的地址”  这样吗？运行一直输出 'cardlistInfo'
然后大佬能不能加个通知推送 青龙有对接 我不会改

**Comment by kuku3863** [comment]
> params =“环境变量的地址” 这样吗？运行一直输出 'cardlistInfo' 然后大佬能不能加个通知推送 青龙有对接 我不会改

pc运行的话，可以看下README.md，我添加了，不懂得地方可以再问问我，推送可以加，我有空就加下推送功能
